# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bubble.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PySide2 import QtGui, QtWidgets, QtCore
from PySide2.QtCore import QSize, Qt
from PySide2.QtWidgets import QApplication, QWidget, QListWidgetItem


class Ui_Form(QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1000, 1000)
        self.chatMsgShowListWidget = QtWidgets.QListWidget(self)
        self.chatMsgShowListWidget.setGeometry(QtCore.QRect(30, 10, 800, 1000))
        self.chatMsgShowListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.chatMsgShowListWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.chatMsgShowListWidget.setObjectName("chatMsgShowListWidget")
        self.chatMsgShowListWidget.setStyleSheet('background-color:#f5f5f5')


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.chatMsgContentLabel.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))

    def refresh_chatMsgShowListWidget(self, userName, msg, isMe=True, msgBgColor='#9eea6a', userHeader='ico/ico.png'):
        lwit = QListWidgetItem()
        self.chatMsgShowListWidget.addItem(lwit)
        if isMe == None:
            mif =self.newMsgItemInformFrame(msg, msgBgColor)
        else:
            mif = self.newMsgItemFrame(userName, msg, isMe, msgBgColor, userHeader)
        lwit.setSizeHint(QSize(400, mif.height()))  # ??

        self.chatMsgShowListWidget.setItemWidget(lwit, mif)
        # self.chatMsgShowListWidget.adjustSize()
        # self.chatMsgShowListWidget.setFixedSize(self.chatMsgShowListWidget.h, self.chatMsgShowListWidget.height())

        # 滚动条到末尾
        self.chatMsgShowListWidget.setCurrentRow(self.chatMsgShowListWidget.count() - 1)

    def newMsgItemFrame(self, userName, msg, isMe, msgBgColor, userHeader):
        '''
        创建消息气泡
        :param userName:用户名
        :param msg: 消息内容
        :param isMe: 是否本人发出的消息，调整控件顺序
        :param msgBgColor: 消息气泡颜色
        :param userHeader: 头像图片路径
        :return: 消息气泡控件
        '''
        chatMsgItemFrame = QtWidgets.QFrame(self)
        chatMsgItemFrame.setGeometry(QtCore.QRect(0, 0, 91, 61))  # ?? ddjust
        chatMsgItemFrame.setStyleSheet("font-size:18pt;")
        chatMsgItemFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        chatMsgItemFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        chatMsgItemFrame.setObjectName("chatMsgItemFrame")
        chatMsgItemFrame.horizontalLayout_4 = QtWidgets.QHBoxLayout(chatMsgItemFrame)
        chatMsgItemFrame.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem_other = QtWidgets.QSpacerItem(92, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        chatMsgItemFrame.vLayyout_middle = QtWidgets.QVBoxLayout()
        chatMsgItemFrame.vLayyout_middle.setObjectName("vLayyout_middle")
        chatMsgItemFrame.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        chatMsgItemFrame.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem_userName = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                                    QtWidgets.QSizePolicy.Minimum)
        chatMsgItemFrame.chatMsgUserNameLabel = QtWidgets.QLabel(chatMsgItemFrame)
        chatMsgItemFrame.chatMsgUserNameLabel.setMinimumSize(QtCore.QSize(0, 16))
        chatMsgItemFrame.chatMsgUserNameLabel.setMaximumSize(QtCore.QSize(16777215, 16))
        chatMsgItemFrame.chatMsgUserNameLabel.setStyleSheet("font:12pt;")
        chatMsgItemFrame.chatMsgUserNameLabel.setText(userName)
        chatMsgItemFrame.chatMsgUserNameLabel.setObjectName("chatMsgUserNameLabel")
        chatMsgItemFrame.vLayyout_middle.addLayout(chatMsgItemFrame.horizontalLayout_3)
        chatMsgItemFrame.chatMsgContentLabel = QtWidgets.QLabel(chatMsgItemFrame)
        chatMsgItemFrame.chatMsgContentLabel.setStyleSheet("background-color:{0};\n"
                                                           "padding:5px;\n"
                                                           "font-size:13pt;\n"
                                                           "border-radius:7px;\n"
                                                           "\n"
                                                           "".format(msgBgColor))
        chatMsgItemFrame.chatMsgContentLabel.setObjectName("chatMsgContentLabel")
        chatMsgItemFrame.chatMsgContentLabel.setText(str(msg))
        chatMsgItemFrame.vLayyout_middle.addWidget(chatMsgItemFrame.chatMsgContentLabel)
        chatMsgItemFrame.vLayout_header = QtWidgets.QVBoxLayout()
        chatMsgItemFrame.vLayout_header.setObjectName("vLayout_header")
        chatMsgItemFrame.chatMsgHeaderLabel = QtWidgets.QLabel(chatMsgItemFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(chatMsgItemFrame.chatMsgHeaderLabel.sizePolicy().hasHeightForWidth())
        chatMsgItemFrame.chatMsgHeaderLabel.setSizePolicy(sizePolicy)
        chatMsgItemFrame.chatMsgHeaderLabel.setMinimumSize(QtCore.QSize(32, 32))
        chatMsgItemFrame.chatMsgHeaderLabel.setMaximumSize(QtCore.QSize(32, 32))
        chatMsgItemFrame.chatMsgHeaderLabel.setStyleSheet("background-color:red")
        chatMsgItemFrame.chatMsgHeaderLabel.setText("")
        chatMsgItemFrame.chatMsgHeaderLabel.setPixmap(
            QtGui.QPixmap(userHeader))
        chatMsgItemFrame.chatMsgHeaderLabel.setScaledContents(True)
        chatMsgItemFrame.chatMsgHeaderLabel.setObjectName("chatMsgHeaderLabel")
        chatMsgItemFrame.vLayout_header.addWidget(chatMsgItemFrame.chatMsgHeaderLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        chatMsgItemFrame.vLayout_header.addItem(spacerItem2)

        if isMe:
            # 偏右
            # 总体布局顺序
            chatMsgItemFrame.horizontalLayout_4.addItem(spacerItem_other)
            chatMsgItemFrame.horizontalLayout_4.addLayout(chatMsgItemFrame.vLayyout_middle)
            chatMsgItemFrame.horizontalLayout_4.addLayout(chatMsgItemFrame.vLayout_header)

            # 用户名布局顺序
            chatMsgItemFrame.horizontalLayout_3.addItem(spacerItem_userName)
            chatMsgItemFrame.horizontalLayout_3.addWidget(chatMsgItemFrame.chatMsgUserNameLabel)

        else:
            # 偏左
            # 总体布局顺序
            chatMsgItemFrame.horizontalLayout_4.addLayout(chatMsgItemFrame.vLayout_header)
            chatMsgItemFrame.horizontalLayout_4.addLayout(chatMsgItemFrame.vLayyout_middle)
            chatMsgItemFrame.horizontalLayout_4.addItem(spacerItem_other)

            # 用户名布局顺序
            chatMsgItemFrame.horizontalLayout_3.addWidget(chatMsgItemFrame.chatMsgUserNameLabel)
            chatMsgItemFrame.horizontalLayout_3.addItem(spacerItem_userName)

        # 根据内容自适应大小
        chatMsgItemFrame.chatMsgContentLabel.setWordWrap(True)
        chatMsgItemFrame.chatMsgContentLabel.adjustSize()
        chatMsgItemFrame.adjustSize()
        return chatMsgItemFrame

    # def newMsgItemFrame(self, userName, msg, isMe, msgBgColor, userHeader):
    #     '''
    #     创建消息气泡
    #     :param userName:用户名
    #     :param msg: 消息内容
    #     :param isMe: 是否本人发出的消息，调整控件顺序
    #     :param msgBgColor: 消息气泡颜色
    #     :param userHeader: 头像图片路径
    #     :return: 消息气泡控件
    #     '''
    #     chatMsgItemFrame = QtWidgets.QFrame(self)
    #     chatMsgItemFrame.setGeometry(QtCore.QRect(0, 0, 91, 61))
    #     chatMsgItemFrame.setStyleSheet("font-size:18pt;")
    #     chatMsgItemFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
    #     chatMsgItemFrame.setFrameShadow(QtWidgets.QFrame.Raised)
    #     chatMsgItemFrame.setObjectName("chatMsgItemFrame")
    #     chatMsgItemFrame.horizontalLayout_4 = QtWidgets.QHBoxLayout(chatMsgItemFrame)
    #     chatMsgItemFrame.horizontalLayout_4.setObjectName("horizontalLayout_4")
    #     spacerItem_other = QtWidgets.QSpacerItem(92, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    #     chatMsgItemFrame.vLayyout_middle = QtWidgets.QVBoxLayout()
    #     chatMsgItemFrame.vLayyout_middle.setObjectName("vLayyout_middle")
    #     chatMsgItemFrame.horizontalLayout_3 = QtWidgets.QHBoxLayout()
    #     chatMsgItemFrame.horizontalLayout_3.setObjectName("horizontalLayout_3")
    #     spacerItem_userName = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
    #     chatMsgItemFrame.chatMsgUserNameLabel = QtWidgets.QLabel(chatMsgItemFrame)
    #     chatMsgItemFrame.chatMsgUserNameLabel.setMinimumSize(QtCore.QSize(0, 16))
    #     chatMsgItemFrame.chatMsgUserNameLabel.setMaximumSize(QtCore.QSize(16777215, 16))
    #     chatMsgItemFrame.chatMsgUserNameLabel.setStyleSheet("font:12pt;")
    #     chatMsgItemFrame.chatMsgUserNameLabel.setText(userName)
    #     chatMsgItemFrame.chatMsgUserNameLabel.setObjectName("chatMsgUserNameLabel")
    #     chatMsgItemFrame.vLayyout_middle.addLayout(chatMsgItemFrame.horizontalLayout_3)
    #     chatMsgItemFrame.chatMsgContentLabel = QtWidgets.QLabel(chatMsgItemFrame)
    #     chatMsgItemFrame.chatMsgContentLabel.setStyleSheet("background-color:{0};\n"
    #                                            "padding:5px;\n"
    #                                            "font-size:11pt;\n"
    #                                             "border-radius:7px;\n"
    #                                            "\n"
    #                                            "".format(msgBgColor))
    #     chatMsgItemFrame.chatMsgContentLabel.setObjectName("chatMsgContentLabel")
    #     # 大小
    #     sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
    #     sizePolicy.setHorizontalStretch(0)
    #     sizePolicy.setVerticalStretch(0)
    #     chatMsgItemFrame.chatMsgContentLabel.setSizePolicy(sizePolicy)
    #
    #     chatMsgItemFrame.chatMsgContentLabel.setText(str(msg))
    #     chatMsgItemFrame.vLayyout_middle.addWidget(chatMsgItemFrame.chatMsgContentLabel)
    #     chatMsgItemFrame.vLayout_header = QtWidgets.QVBoxLayout()
    #     chatMsgItemFrame.vLayout_header.setObjectName("vLayout_header")
    #     chatMsgItemFrame.chatMsgHeaderLabel = QtWidgets.QLabel(chatMsgItemFrame)
    #     sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    #     sizePolicy.setHorizontalStretch(0)
    #     sizePolicy.setVerticalStretch(0)
    #     sizePolicy.setHeightForWidth(chatMsgItemFrame.chatMsgHeaderLabel.sizePolicy().hasHeightForWidth())
    #     chatMsgItemFrame.chatMsgHeaderLabel.setSizePolicy(sizePolicy)
    #     chatMsgItemFrame.chatMsgHeaderLabel.setMinimumSize(QtCore.QSize(32, 32))
    #     chatMsgItemFrame.chatMsgHeaderLabel.setMaximumSize(QtCore.QSize(32, 32))
    #     chatMsgItemFrame.chatMsgHeaderLabel.setStyleSheet("background-color:red")
    #     chatMsgItemFrame.chatMsgHeaderLabel.setText("")
    #     chatMsgItemFrame.chatMsgHeaderLabel.setPixmap(
    #         QtGui.QPixmap(userHeader))
    #     chatMsgItemFrame.chatMsgHeaderLabel.setScaledContents(True)
    #     chatMsgItemFrame.chatMsgHeaderLabel.setObjectName("chatMsgHeaderLabel")
    #     chatMsgItemFrame.vLayout_header.addWidget(chatMsgItemFrame.chatMsgHeaderLabel)
    #     spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
    #     chatMsgItemFrame.vLayout_header.addItem(spacerItem2)
    #
    #     if isMe:
    #         # 总体布局顺序
    #         chatMsgItemFrame.horizontalLayout_4.addLayout(chatMsgItemFrame.vLayout_header)
    #         chatMsgItemFrame.horizontalLayout_4.addLayout(chatMsgItemFrame.vLayyout_middle)
    #         chatMsgItemFrame.horizontalLayout_4.addItem(spacerItem_other)
    #
    #         # 用户名布局顺序
    #         chatMsgItemFrame.horizontalLayout_3.addWidget(chatMsgItemFrame.chatMsgUserNameLabel)
    #         chatMsgItemFrame.horizontalLayout_3.addItem(spacerItem_userName)
    #
    #     else:
    #         # 总体布局顺序
    #         chatMsgItemFrame.horizontalLayout_4.addItem(spacerItem_other)
    #         chatMsgItemFrame.horizontalLayout_4.addLayout(chatMsgItemFrame.vLayyout_middle)
    #         chatMsgItemFrame.horizontalLayout_4.addLayout(chatMsgItemFrame.vLayout_header)
    #
    #         # 用户名布局顺序
    #         chatMsgItemFrame.horizontalLayout_3.addItem(spacerItem_userName)
    #         chatMsgItemFrame.horizontalLayout_3.addWidget(chatMsgItemFrame.chatMsgUserNameLabel)
    #
    #     # 内容自适应
    #     chatMsgItemFrame.chatMsgContentLabel.adjustSize()
    #     chatMsgItemFrame.adjustSize()
    #     return chatMsgItemFrame

    def newMsgItemInformFrame(self, msg, msgBgColor):
        chatMsgItemFrame = QtWidgets.QFrame(self)
        chatMsgItemFrame.setGeometry(QtCore.QRect(0, 0, 91, 61))  # ?? ddjust
        chatMsgItemFrame.setStyleSheet("font-size:18pt;")
        chatMsgItemFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        chatMsgItemFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        chatMsgItemFrame.setObjectName("chatMsgItemFrame")
        horizontalLayout_4 = QtWidgets.QHBoxLayout(chatMsgItemFrame)
        horizontalLayout_4.setObjectName("horizontalLayout_4")

        chatMsgContentLabel = QtWidgets.QLabel()
        horizontalLayout_4.addWidget(chatMsgContentLabel)
        chatMsgContentLabel.setStyleSheet("background-color:{0};\n"
                                                           "padding:5px;\n"
                                                           "font-size:13pt;\n"
                                                           "border-radius:7px;\n"
                                                           "\n"
                                                           "".format(msgBgColor))
        chatMsgContentLabel.setObjectName("chatMsgContentLabel")
        chatMsgContentLabel.setText(str(msg))
        # chatMsgContentLabel.setWordWrap(True)
        chatMsgContentLabel.adjustSize()
        chatMsgContentLabel.setFixedSize(chatMsgContentLabel.width(), chatMsgContentLabel.height())
        return chatMsgItemFrame

if __name__ == '__main__':
    app = QApplication([])
    ui = Ui_Form()
    ui.show()
    ui.refresh_chatMsgShowListWidget('狗头人', '''a''', False, 'white')
    ui.refresh_chatMsgShowListWidget('狗头人', 'a', False, 'white')
    ui.refresh_chatMsgShowListWidget('狗头人', '''aefe''')
    ui.refresh_chatMsgShowListWidget('莫', '鸟儿建瓯放假哦分节符案件偶分二级佛就', None, '#dadada')
    ui.refresh_chatMsgShowListWidget('狗头人', '''aef''')
    ui.refresh_chatMsgShowListWidget('狗头人', '''aefefefcvhiahfcvncz,nefh,mcnka\nefefkhfekasknfa\t''')
    ui.refresh_chatMsgShowListWidget('狗头人', '''aefefefcvhiah\tfcvn\n\ncz,n\n\n\nefh,mcnka\nefefkhfekasknfa\t''', False, 'white')
    ui.refresh_chatMsgShowListWidget('狗头人', '''aefefefcvhiann\n\n\n\nhfcvncz,nefh,mcnka\nefefkhfekasknfa\t''')
    ui.refresh_chatMsgShowListWidget('狗头人', '''aefefefcvhiahf\ncvncz,nefh,mcnka\nefefkhfekasknfa\t''')
    ui.refresh_chatMsgShowListWidget('狗头人', '''aefefefcvhiahfcvncz,nefh,mcnka\nefefkhfekasknfa\t''')
    sys.exit(app.exec_())

