# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filedowndlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PySide2 import QtGui, QtWidgets, QtCore
from PySide2.QtCore import Signal, Qt
from PySide2.QtWidgets import QDialog, QApplication, QMessageBox


class Ui_FileDownDlg(QDialog):
    signal_on_recvStopPushButton_click = Signal(str, bool)

    def __init__(self):
        super().__init__()
        self.setupUi()
        self.bindSlots()
        self.setAttribute(Qt.WA_DeleteOnClose)

    def setupUi(self):
        self.setObjectName("FileDownDlg")
        self.resize(440, 210)
        self.recvProgressBar = QtWidgets.QProgressBar(self)
        self.recvProgressBar.setGeometry(QtCore.QRect(100, 160, 231, 23))
        self.recvProgressBar.setProperty("value", 0)
        self.recvProgressBar.setObjectName("recvProgressBar")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(170, 15, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.rfileNameLineEdit = QtWidgets.QLineEdit(self)
        self.rfileNameLineEdit.setEnabled(False)
        self.rfileNameLineEdit.setGeometry(QtCore.QRect(100, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.rfileNameLineEdit.setFont(font)
        self.rfileNameLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rfileNameLineEdit.setReadOnly(True)
        self.rfileNameLineEdit.setObjectName("rfileNameLineEdit")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rfileSizeLineEdit = QtWidgets.QLineEdit(self)
        self.rfileSizeLineEdit.setEnabled(False)
        self.rfileSizeLineEdit.setGeometry(QtCore.QRect(100, 110, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.rfileSizeLineEdit.setFont(font)
        self.rfileSizeLineEdit.setText("")
        self.rfileSizeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rfileSizeLineEdit.setReadOnly(True)
        self.rfileSizeLineEdit.setObjectName("rfileSizeLineEdit")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(30, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.rateLabel = QtWidgets.QLabel(self)
        self.rateLabel.setGeometry(QtCore.QRect(340, 160, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.rateLabel.setFont(font)
        self.rateLabel.setText("")
        self.rateLabel.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.rateLabel.setObjectName("rateLabel")
        self.recvStopPushButton = QtWidgets.QPushButton(self)
        self.recvStopPushButton.setGeometry(QtCore.QRect(340, 150, 75, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.recvStopPushButton.setFont(font)
        self.recvStopPushButton.setObjectName("recvStopPushButton")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, FileDownDlg):
        _translate = QtCore.QCoreApplication.translate
        FileDownDlg.setWindowTitle(_translate("FileDownDlg", "接 收 文 件"))
        self.label.setText(_translate("FileDownDlg", "文 件 接 收"))
        self.label_2.setText(_translate("FileDownDlg", "接 收 文 件"))
        self.label_3.setText(_translate("FileDownDlg", "大     小："))
        self.label_5.setText(_translate("FileDownDlg", "进         度"))
        self.recvStopPushButton.setText(_translate("FileDownDlg", "停止"))

    def bindSlots(self):
        self.recvStopPushButton.clicked.connect(self.on_recvStopPushButton_click)

    def refresh_recvFileLineEdit(self, filePath, fileSizeTotal):
        self.rfileNameLineEdit.setText(filePath)
        self.rfileSizeLineEdit.setText(fileSizeTotal)

    def refresh_recvProgressBar(self, curPercent):
        QApplication.processEvents()
        self.recvProgressBar.setValue(curPercent)
        if (100 == curPercent):
            QMessageBox.information(self, '提示', '文件成功下载')

    def on_recvStopPushButton_click(self):
        self.signal_on_recvStopPushButton_click.emit(self.rfileNameLineEdit.text(), False)

    def closeEvent(self, a0: QtGui.QCloseEvent) -> None:
        self.recvStopPushButton.click()
        super().closeEvent(a0)


if __name__ == '__main__':
    app = QApplication([])
    ui = Ui_FileDownDlg()
    ui.show()
    sys.exit(app.exec_())
