# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filesupdlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtGui, QtWidgets, QtCore
from PySide2.QtCore import Signal, Qt
from PySide2.QtWidgets import QDialog, QApplication, QMessageBox


class Ui_FileUpDlg(QDialog):
    signal_on_sendStopPushButton_click = Signal(str, bool)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowFlags(self.windowFlags() | (Qt.WindowMinimizeButtonHint | Qt.WindowCloseButtonHint) & ~(
                    Qt.WindowContextHelpButtonHint | Qt.WindowMaximizeButtonHint))
        self.setupUi()
        self.bindSlots()
        self.setAttribute(Qt.WA_DeleteOnClose)

    def setupUi(self):
        self.setObjectName("FileUpDlg")
        self.resize(440, 210)
        self.sendProgressBar = QtWidgets.QProgressBar(self)
        self.sendProgressBar.setGeometry(QtCore.QRect(100, 160, 241, 23))
        self.sendProgressBar.setProperty("value", 0)
        self.sendProgressBar.setObjectName("sendProgressBar")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(170, 15, 91, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.sfileNameLineEdit = QtWidgets.QLineEdit(self)
        self.sfileNameLineEdit.setEnabled(False)
        self.sfileNameLineEdit.setGeometry(QtCore.QRect(100, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.sfileNameLineEdit.setFont(font)
        self.sfileNameLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sfileNameLineEdit.setReadOnly(True)
        self.sfileNameLineEdit.setObjectName("sfileNameLineEdit")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 51, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.sfileSizeLineEdit = QtWidgets.QLineEdit(self)
        self.sfileSizeLineEdit.setEnabled(False)
        self.sfileSizeLineEdit.setGeometry(QtCore.QRect(100, 110, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.sfileSizeLineEdit.setFont(font)
        self.sfileSizeLineEdit.setText("")
        self.sfileSizeLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.sfileSizeLineEdit.setReadOnly(True)
        self.sfileSizeLineEdit.setObjectName("sfileSizeLineEdit")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(30, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.sendStopPushButton = QtWidgets.QPushButton(self)
        self.sendStopPushButton.setGeometry(QtCore.QRect(340, 150, 75, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sendStopPushButton.setFont(font)
        self.sendStopPushButton.setObjectName("sendStopPushButton")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, FileUpDlg):
        _translate = QtCore.QCoreApplication.translate
        FileUpDlg.setWindowTitle(_translate("FileUpDlg", "发 送 文 件"))
        self.label.setText(_translate("FileUpDlg", "文 件 发 送"))
        self.label_2.setText(_translate("FileUpDlg", "发 送 文 件"))
        self.label_3.setText(_translate("FileUpDlg", "大   小："))
        self.label_5.setText(_translate("FileUpDlg", "进         度"))
        self.sendStopPushButton.setText(_translate("FileUpDlg", "停止"))

    def bindSlots(self):
        self.sendStopPushButton.clicked.connect(self.on_sendStopPushButton_click)

    def refresh_sendfileLineEdit(self, filePath, fileSizeTotal):
        self.sfileNameLineEdit.setText(filePath)
        print('ui_openFile:', fileSizeTotal)
        self.sfileSizeLineEdit.setText(fileSizeTotal)

    def refresh_sendProgressBar(self, curPercent):
        QApplication.processEvents()
        self.sendProgressBar.setValue(curPercent)
        if (100 == curPercent):
            QMessageBox.information(self, '提示', '文件成功上传')

    def getFileName(self):
        return self.sfileNameLineEdit.text()

    def on_sendStopPushButton_click(self):
        # if(QMessageBox.Yes == QMessageBox.question(self, '警告', '是否停止文件上传？', QMessageBox.Yes | QMessageBox.Cancel)):
        self.signal_on_sendStopPushButton_click.emit(self.getFileName(), True)

    def closeEvent(self, a0: QtGui.QCloseEvent) -> None:
        super().closeEvent(a0)
        self.sendStopPushButton.click()


if __name__ == '__main__':
    app = QApplication([])
    ui = Ui_FileUpDlg()
    ui.show()
    app.exec_()
