# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logindlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import traceback

from PySide2 import QtGui, QtWidgets, QtCore
from PySide2.QtCore import Qt
from PySide2.QtWidgets import QDialog, QApplication, QMessageBox


class Ui_LoginDlg(QDialog):
    isExit = True # 退出程序
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.setAttribute(Qt.WA_DeleteOnClose) # 关闭后清除内存

    def setupUi(self):
        self.setObjectName("LoginDlg")
        self.resize(293, 179)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(293, 179))
        self.setMaximumSize(QtCore.QSize(293, 179))
        self.setStyleSheet("")
        self.loginBGLabel = QtWidgets.QLabel(self)
        self.loginBGLabel.setGeometry(QtCore.QRect(0, 0, 293, 179))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginBGLabel.sizePolicy().hasHeightForWidth())
        self.loginBGLabel.setSizePolicy(sizePolicy)
        self.loginBGLabel.setStyleSheet("\n"
"background-repeat:no-repeat;")
        self.loginBGLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.loginBGLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.loginBGLabel.setText("")
        self.loginBGLabel.setPixmap(QtGui.QPixmap(":/pic/login.jpg"))
        self.loginBGLabel.setObjectName("loginBGLabel")
        self.usrLineEdit = QtWidgets.QLineEdit(self)
        self.usrLineEdit.setGeometry(QtCore.QRect(110, 65, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.usrLineEdit.setFont(font)
        self.usrLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.usrLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.usrLineEdit.setObjectName("usrLineEdit")
        self.servAddrLineEdit = QtWidgets.QLineEdit(self)
        self.servAddrLineEdit.setGeometry(QtCore.QRect(110, 35, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.servAddrLineEdit.setFont(font)
        self.servAddrLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.servAddrLineEdit.setObjectName("servAddrLineEdit")
        self.loginPushButton = QtWidgets.QPushButton(self)
        self.loginPushButton.setGeometry(QtCore.QRect(40, 100, 212, 43))
        self.loginPushButton.setFlat(False)
        self.loginPushButton.setObjectName("loginPushButton")
        self.servAddrLabel = QtWidgets.QLabel(self)
        self.servAddrLabel.setGeometry(QtCore.QRect(50, 40, 54, 12))
        self.servAddrLabel.setObjectName("servAddrLabel")
        self.usrLabel = QtWidgets.QLabel(self)
        self.usrLabel.setGeometry(QtCore.QRect(50, 70, 54, 12))
        self.usrLabel.setObjectName("usrLabel")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, LoginDlg):
        _translate = QtCore.QCoreApplication.translate
        LoginDlg.setWindowTitle(_translate("LoginDlg", "连接"))
        self.servAddrLineEdit.setText(_translate("LoginDlg", "127.0.0.1:8808"))
        self.servAddrLineEdit.setPlaceholderText(_translate("LoginDlg", "127.0.0.1:8808"))
        self.loginPushButton.setText(_translate("LoginDlg", "登录"))
        self.servAddrLabel.setText(_translate("LoginDlg", "服务器IP："))
        self.usrLabel.setText(_translate("LoginDlg", "用 户 名："))

    def getLoginInfo(self):
        userName = self.usrLineEdit.text().strip()
        serverAddr = self.servAddrLineEdit.text().strip().split(':')
        if not userName:
            QMessageBox.critical(self, '警告', '用户名不能为空')
            return None
        if(2 != len(serverAddr)):
            QMessageBox.critical(self, '警告', '服务器地址格式错误！')
            return None
        try:
            serverAddr[1] = int(serverAddr[1])
            if(serverAddr[1] < 0 or serverAddr[1]>65535):
                QMessageBox.critical(self, '警告', '端口号超出范围(0-65535)！')
                return None
        except ValueError as e:
            print('【已捕获异常】')
            traceback.print_exc()
            QMessageBox.critical(self, '警告', '服务器地址格式错误！')
            return None
        return (userName, tuple(serverAddr))

    def closeEvent(self, a0: QtGui.QCloseEvent) -> None:
        super().closeEvent(a0)
        if(self.isExit):
            sys.exit(0)


if __name__ == '__main__':
    app = QApplication([])
    ui = Ui_LoginDlg()
    ui.setupUi()
    ui.show()
    app.exec_()