# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logindlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication


class Ui_LoginDlg(QDialog):

    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("LoginDlg")
        self.resize(281, 400)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(0, 0, 280, 400))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/pic/login.jpg"))
        self.label.setObjectName("label")
        self.usrLineEdit = QtWidgets.QLineEdit(self)
        self.usrLineEdit.setGeometry(QtCore.QRect(85, 215, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.usrLineEdit.setFont(font)
        self.usrLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.usrLineEdit.setObjectName("usrLineEdit")
        self.pwdLineEdit = QtWidgets.QLineEdit(self)
        self.pwdLineEdit.setGeometry(QtCore.QRect(85, 235, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pwdLineEdit.setFont(font)
        self.pwdLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.pwdLineEdit.setObjectName("pwdLineEdit")
        self.loginPushButton = QtWidgets.QPushButton(self)
        self.loginPushButton.setGeometry(QtCore.QRect(36, 258, 212, 43))
        self.loginPushButton.setFlat(False)
        self.loginPushButton.setObjectName("loginPushButton")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, LoginDlg):
        _translate = QtCore.QCoreApplication.translate
        LoginDlg.setWindowTitle(_translate("LoginDlg", "Dialog"))
        self.loginPushButton.setText(_translate("LoginDlg", "登录"))


if __name__ == '__main__':
    app = QApplication([])
    ui = Ui_LoginDlg()
    ui.setupUi()
    # ui.loginPushButton.clicked.connect(check)
    ui.show()
    app.exec_()
