# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtCore import pyqtSlot, pyqtSignal
from PyQt5.QtWidgets import QApplication, QWidget, QAbstractItemView, QHeaderView, QPushButton, \
    QTableWidgetItem, QTableWidget


class Ui_MainBoard(QWidget):
    signal_refresh_chatMsgShowTextBrowser = pyqtSignal(str)
    signal_refresh_filesShowTableWidget = pyqtSignal(dict)

    def __init__(self):
        super().__init__()
        self.setupUi()
        self.bindSlot()

    def setupUi(self):
        self.setObjectName("MainBoard")
        self.resize(836, 774)
        self.setStyleSheet("* {\n"
                           "font: 12pt \"Consolas\";\n"
                           "}\n"
                           "\n"
                           "")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.chatTab = QtWidgets.QWidget()
        self.chatTab.setStyleSheet("background-color: rgb(216, 205, 237);")
        self.chatTab.setObjectName("chatTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.chatTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chatMsgShowTextBrowser = QtWidgets.QTextBrowser(self.chatTab)
        self.chatMsgShowTextBrowser.setObjectName("chatMsgShowTextBrowser")
        self.horizontalLayout_3.addWidget(self.chatMsgShowTextBrowser)
        self.chatUserOnLineTableWidget = QtWidgets.QTableWidget(self.chatTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatUserOnLineTableWidget.sizePolicy().hasHeightForWidth())
        self.chatUserOnLineTableWidget.setSizePolicy(sizePolicy)
        self.chatUserOnLineTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.chatUserOnLineTableWidget.setObjectName("chatUserOnLineTableWidget")
        self.chatUserOnLineTableWidget.setColumnCount(1)
        self.chatUserOnLineTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.chatUserOnLineTableWidget.setHorizontalHeaderItem(0, item)
        self.chatUserOnLineTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.chatUserOnLineTableWidget.horizontalHeader().setStretchLastSection(True)
        self.chatUserOnLineTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.chatUserOnLineTableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_3.addWidget(self.chatUserOnLineTableWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.chatTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.groupBox_3 = QtWidgets.QGroupBox(self.chatTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chatFileUploadPushButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatFileUploadPushButton.sizePolicy().hasHeightForWidth())
        self.chatFileUploadPushButton.setSizePolicy(sizePolicy)
        self.chatFileUploadPushButton.setObjectName("chatFileUploadPushButton")
        self.horizontalLayout.addWidget(self.chatFileUploadPushButton)
        self.chatImageUploadPushButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatImageUploadPushButton.sizePolicy().hasHeightForWidth())
        self.chatImageUploadPushButton.setSizePolicy(sizePolicy)
        self.chatImageUploadPushButton.setObjectName("chatImageUploadPushButton")
        self.horizontalLayout.addWidget(self.chatImageUploadPushButton)
        self.chatCapturePushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.chatCapturePushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatCapturePushButton.sizePolicy().hasHeightForWidth())
        self.chatCapturePushButton.setSizePolicy(sizePolicy)
        self.chatCapturePushButton.setObjectName("chatCapturePushButton")
        self.horizontalLayout.addWidget(self.chatCapturePushButton)
        spacerItem = QtWidgets.QSpacerItem(699, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.chatMsgEditTextEdit = QtWidgets.QTextEdit(self.chatTab)
        self.chatMsgEditTextEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.chatMsgEditTextEdit.sizePolicy().hasHeightForWidth())
        self.chatMsgEditTextEdit.setSizePolicy(sizePolicy)
        self.chatMsgEditTextEdit.setObjectName("chatMsgEditTextEdit")
        self.verticalLayout.addWidget(self.chatMsgEditTextEdit)
        self.line_3 = QtWidgets.QFrame(self.chatTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.chatSendPushButton = QtWidgets.QPushButton(self.chatTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chatSendPushButton.sizePolicy().hasHeightForWidth())
        self.chatSendPushButton.setSizePolicy(sizePolicy)
        self.chatSendPushButton.setStyleSheet("background-color: rgb(102, 58, 183);\n"
                                              "color:rgb(255, 255, 255);\n"
                                              "\n"
                                              "\n"
                                              "/* border:5px, solid, rgb(0, 0, 0);*/\n"
                                              "")
        self.chatSendPushButton.setObjectName("chatSendPushButton")
        self.verticalLayout.addWidget(self.chatSendPushButton, 0, QtCore.Qt.AlignRight)
        self.line_2 = QtWidgets.QFrame(self.chatTab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.tabWidget.addTab(self.chatTab, "")
        self.noticeTab = QtWidgets.QWidget()
        self.noticeTab.setObjectName("noticeTab")
        self.noticePushButton = QtWidgets.QPushButton(self.noticeTab)
        self.noticePushButton.setGeometry(QtCore.QRect(410, 200, 61, 31))
        self.noticePushButton.setObjectName("noticePushButton")
        self.tabWidget.addTab(self.noticeTab, "")
        self.fileTab = QtWidgets.QWidget()
        self.fileTab.setObjectName("fileTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fileTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filesNumLabel = QtWidgets.QLabel(self.fileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesNumLabel.sizePolicy().hasHeightForWidth())
        self.filesNumLabel.setSizePolicy(sizePolicy)
        self.filesNumLabel.setObjectName("filesNumLabel")
        self.horizontalLayout_2.addWidget(self.filesNumLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit = QtWidgets.QLineEdit(self.fileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.filesUploadPushButton = QtWidgets.QPushButton(self.fileTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesUploadPushButton.sizePolicy().hasHeightForWidth())
        self.filesUploadPushButton.setSizePolicy(sizePolicy)
        self.filesUploadPushButton.setStyleSheet("background-color:rgb(18, 183, 245);\n"
                                                 "color:rgb(255, 255, 255)")
        self.filesUploadPushButton.setObjectName("filesUploadPushButton")
        self.horizontalLayout_2.addWidget(self.filesUploadPushButton)
        self.filesFlushPushButton = QtWidgets.QPushButton(self.fileTab)
        self.filesFlushPushButton.setObjectName("filesFlushPushButton")
        self.horizontalLayout_2.addWidget(self.filesFlushPushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.filesShowTableWidget = QtWidgets.QTableWidget(self.fileTab)
        self.filesShowTableWidget.setEnabled(True)
        self.filesShowTableWidget.setMinimumSize(QtCore.QSize(600, 500))
        self.filesShowTableWidget.setObjectName("filesShowTableWidget")
        self.filesShowTableWidget.setColumnCount(5)
        self.filesShowTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.filesShowTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesShowTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesShowTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesShowTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.filesShowTableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.filesShowTableWidget)
        self.tabWidget.addTab(self.fileTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(self)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainBoard):
        _translate = QtCore.QCoreApplication.translate
        MainBoard.setWindowTitle(_translate("MainBoard", "月聊天室"))
        item = self.chatUserOnLineTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainBoard", "在线用户"))
        self.groupBox_3.setTitle(_translate("MainBoard", "GroupBox"))
        self.chatFileUploadPushButton.setText(_translate("MainBoard", "上传文件"))
        self.chatImageUploadPushButton.setText(_translate("MainBoard", "上传图片"))
        self.chatCapturePushButton.setToolTip(_translate("MainBoard", "截图"))
        self.chatCapturePushButton.setText(_translate("MainBoard", "截图"))
        self.chatMsgEditTextEdit.setHtml(_translate("MainBoard",
                                                    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.chatMsgEditTextEdit.setPlaceholderText(_translate("MainBoard", "请输入"))
        self.chatSendPushButton.setText(_translate("MainBoard", "发送"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chatTab), _translate("MainBoard", "聊天"))
        self.noticePushButton.setText(_translate("MainBoard", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.noticeTab), _translate("MainBoard", "公告"))
        self.filesNumLabel.setText(_translate("MainBoard", "共x个文件"))
        self.lineEdit.setPlaceholderText(_translate("MainBoard", "搜索"))
        self.filesUploadPushButton.setText(_translate("MainBoard", "十 上传"))
        self.filesFlushPushButton.setText(_translate("MainBoard", "刷新"))
        item = self.filesShowTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainBoard", "文件"))
        item = self.filesShowTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainBoard", "更新时间"))
        item = self.filesShowTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainBoard", "大小"))
        item = self.filesShowTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainBoard", "上传者"))
        item = self.filesShowTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainBoard", "-"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fileTab), _translate("MainBoard", "文件"))

    def bindSlot(self):
        self.signal_refresh_chatMsgShowTextBrowser.connect(self.refresh_chatMsgShowTextBrowser)
        self.signal_refresh_filesShowTableWidget.connect(self.refresh_filesShowTableWidget)
        self.tabWidget.currentChanged.connect(self.on_changeTabWidget)

    def on_changeTabWidget(self):
        if (2 == self.tabWidget.currentIndex()):
            self.filesFlushPushButton.click()

    @pyqtSlot(str)
    def refresh_chatMsgShowTextBrowser(self, msg):
        msg = msg.replace('\n', '<br/>')
        msg = msg.replace('\t', '&emsp;')
        msgHtml = '<p style="color:#0000CD;font-size:18px;background-color:#D9D9D9;">%s</p><br/>' % (msg)
        print(msgHtml)
        self.chatMsgShowTextBrowser.append(msgHtml)

    @pyqtSlot(dict)
    def refresh_filesShowTableWidget(self, filesAndDirs):
        fv = self.filesShowTableWidget
        fv.setRowCount(0)  # 清空旧数据
        fv.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.filesNumLabel.setText('共' + str(filesAndDirs['filesNum']) + '个文件')
        for fileInfo in filesAndDirs['files']:
            # 获取文件属性
            fileName = fileInfo['fileName']
            modifyTime = fileInfo['modifyTime']
            fileSize = round(fileInfo['fileSize']/1024, 2)
            print(fileName, modifyTime, fileSize)

            rowPosition = fv.rowCount()
            fv.insertRow(rowPosition)
            fv.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)

            # 动态生成按钮
            fileDownloadPushButton = QPushButton(text='下载')
            fileDeletePushButton = QPushButton(text='删除')
            # fileDownloadPushButton.clicked.connect(functools.partial(self.on_btn_file_download_clicked, fileName))
            # fileDeletePushButton.clicked.connect(functools.partial(self.on_btn_file_delete_clicked, rowPosition))

            # 插入列数据
            fv.setItem(rowPosition, 0, QTableWidgetItem(fileName))
            fv.setItem(rowPosition, 1, QTableWidgetItem(modifyTime))
            fv.setItem(rowPosition, 2, QTableWidgetItem(str(fileSize) + 'KB'))
            fv.setCellWidget(rowPosition, 3, fileDownloadPushButton)
            fv.setCellWidget(rowPosition, 4, fileDeletePushButton)

            # 设置列宽
            QTableWidget.horizontalHeader(fv).resizeSection(1, 100)
            QTableWidget.horizontalHeader(fv).resizeSection(3, 70)
            QTableWidget.horizontalHeader(fv).resizeSection(4, 70)

    def refresh_chatUserOnLineTableWidget(self, userOnlineList):
        uv = self.chatUserOnLineTableWidget
        uv.setRowCount(0)
        uv.setEditTriggers(QAbstractItemView.NoEditTriggers)
        for userName in userOnlineList:
            # print(userName, userOnlineList[userName])

            rowPosition = uv.rowCount()
            uv.insertRow(rowPosition)
            uv.setItem(rowPosition, 0, QTableWidgetItem(userName))

    def closeEvent(self, a0: QtGui.QCloseEvent) -> None:
        super().closeEvent(a0)


if __name__ == '__main__':
    app = QApplication([])
    ui = Ui_MainBoard()
    ui.setupUi()
    ui.show()
    app.exec_()
